accounts/urls.py
from django.urls import path, include
from .import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name ="login"),
    path('logout/', views.logout_view, name="logout"),
    
]

calculators/urls.py
from django.urls import path
from .import views

app_name = 'calculators'

urlpatterns = [
    path('', views.calculators_list, name = 'list'),
    path('<slug:slug>/', views.calculator_detail, name = "detail"),

]

conversion/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from calculators import views as calculator_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('calculators/', include('calculators.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.homepage, name = 'home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

calculators/models.py
from django.db import models

class Calculator(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	#optional thumbnail might delete
	thumb = models.ImageField(default='default.png', blank = True)

	def __str__(self):
		return self.title

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_view(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			#log user in
			login(request, user)
			return redirect('home')
	else:
		form = UserCreationForm()
	return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#login in the user
			user = form.get_user()
			login(request, user)
			return redirect('home')
	else:
		form = AuthenticationForm()
	return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('home')

calculators/views.py
from django.shortcuts import render
from .models import Calculator
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required(login_url="/accounts/login/")
def calculators_list(request):
	calculator = Calculator.objects.all().order_by('title')
	return render(request, 'calculators/calculators_list.html',{'calculator': calculator})

@login_required(login_url="/accounts/login/")
def calculator_detail(request,slug):
	calcs = Calculator.objects.get(slug=slug)
	
	if calcs.slug == 'weight-calculator':
		return render(request, 'calculators/weight.html',{'calcs':calcs})
	elif calcs.slug == 'temperature-calculator':
		return render(request, 'calculators/temp.html',{'calcs':calcs})
	elif calcs.slug == 'length-calculator':
		return render(request, 'calculators/length.html',{'calcs':calcs})
	else:
		return render(request, 'calculators/calculators_detail.html',{'calcs':calcs})

conversion/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
	return render(request, 'homepage.html')

accounts/templates/accounts/login.html
{%extends 'base_layout.html'%}


{%block content%}
		<h1>Log in</h1>
		<form class= 'site-form' action ="{% url 'accounts:login'%}" method="post">
		{%csrf_token%}
		{{form}}
		<input type="submit" value="Login">
		</form>
{%endblock%}

accounts/templates/accounts/signup.html
{%extends 'base_layout.html'%}


{%block content%}

<h1>Signup</h1>
<form class= "site-form" action ="{% url 'accounts:signup'%}" method="post">
	{%csrf_token%}
	{{form}}
	<input type="submit" value="Signup">
</form>


{%endblock%}

calculators/templates/calculators/calculators_detail.html
{%extends 'base_layout.html'%}


{%block content%}

<div class= 'calculator-detail'>
<div class = 'calc-detail'>
	<img src="{{calcs.thumb.url}}"/>
	<h2> {{calcs.title}}</h2>
	<p>This conversion calculator is coming soon!</p>


</div>	
</div>

{%endblock%}

calculators/templates/calculators/calculators_list.html
{%extends 'base_layout.html'%}

{%block content%}
	<h1>Calculator List</h1>
	<div class = 'calculators'>
	{% for calc in calculator %}
		<div class= 'calculator'>
			<h2 >
				<a href="{%url 'calculators:detail' slug=calc.slug%}"> 
					{{calc.title}} 
					<img  class="list-img" src="{{calc.thumb.url}}"/>
				</a>
			</h2>
		</div>
	{%endfor%}
	</div>
{%endblock%}

calculators/templates/calculators/length.html
{%extends 'base_layout.html'%}

{%block content%}

  <div class="calc-function">
    <img class="list-img" src="{{calcs.thumb.url}}"/>
    <p> Type a value in the Miles or Kilometers text field</p>
    <form>
    <div class="fields">
      <label>Kilometers</label>
      <input class="field-input" id="inputKilometers" type="number" placeholder="Kilometers" oninput="lengthConverter(this.id,this.value)" onchange="lengthConverter(this.id,this.value)">
    </div>
    <div class="fields">
      <label>Miles</label>
      <input class="field-input" id="inputMiles" type="number" placeholder="Miles" oninput="lengthConverter(this.id,this.value)" onchange="lengthConverter(this.id,this.value)">
    </div>
     <div class="clear-field">
      <button type="reset" value="reset">Reset</button>
    </div>
    </form>
  </div>


<script>
function lengthConverter(source,valNum) {
  valNum = parseFloat(valNum);
  var inputKilometers = document.getElementById("inputKilometers");
  var inputMiles = document.getElementById("inputMiles");
  
  if (source=="inputKilometers") {
    inputMiles.value=(valNum*0.62137).toFixed(2);    
  }
  if (source=="inputMiles") {
    inputKilometers.value=(valNum/0.62137).toFixed(2);    
  }
}
</script>

{%endblock%}

calculators/templates/calculators/temp.html
{%extends 'base_layout.html'%}

{%block content%}

  <div class="calc-function">
    <img class= "list-img" src="{{calcs.thumb.url}}"/>
    <p> Type a value in the Fahrenheit or Celsius text field</p>
       
    <form>
    <div class="fields">
      <label>Fahrenheit</label>
      <input class="field-input" id="inputFahrenheit"  type="number" min="-459.66999999999996" placeholder="Fahrenheit" oninput="temperatureConverter(this.id,this.value)" onchange="temperatureConverter(this.id,this.value)">
    </div>
    <div class="fields">
      <label>Celsius</label>
      <input class="field-input" id="inputCelsius" type="number" min="-273.15" placeholder="Celsius" oninput="temperatureConverter(this.id,this.value)" onchange="temperatureConverter(this.id,this.value)">
    </div>
    <div class="clear-field">
      <button type="reset" value="reset">Reset</button>
    </div>
    </form>
  </div>


<script>
function temperatureConverter(source,valNum) {
  valNum = parseFloat(valNum);
  var inputFahrenheit = document.getElementById("inputFahrenheit");
  var inputCelsius = document.getElementById("inputCelsius");
  if (source=="inputFahrenheit") {
    inputCelsius.value=((valNum-32)/1.8).toFixed(2);
  }
  if (source=="inputCelsius") {
    inputFahrenheit.value=((valNum*1.8)+32).toFixed(2);
  }
}
</script>


{%endblock%}

calculators/templates/calculators/weight.html
{%extends 'base_layout.html'%}

{%block content%}

  <div class="calc-function">
    <img src="{{calcs.thumb.url}}"/>
    <p> Type a value in the Pounds or Kilograms text field</p>
    <form>
    <div class="fields">
      <label>Pounds</label>
      <input class="field-input" id="inputPounds" type="number" placeholder="Pounds" oninput="weightConverter(this.id,this.value)" onchange="weightConverter(this.id,this.value)">
    </div>
    <div class="fields">
      <label>Kilograms</label>
      <input class="field-input" id="inputKilograms" type="number" placeholder="Kilograms" oninput="weightConverter(this.id,this.value)" onchange="weightConverter(this.id,this.value)">
    </div>
     <div class="clear-field">
      <button type="reset" value="reset">Reset</button>
    </div>
    </form>
  
  </div>

<script>
function weightConverter(source,valNum) {
  valNum = parseFloat(valNum);
  var inputPounds = document.getElementById("inputPounds");
  var inputKilograms = document.getElementById("inputKilograms");
  if (source=="inputPounds") {
    inputKilograms.value=(valNum/2.2046).toFixed(2);
  }
  if (source=="inputKilograms") {
    inputPounds.value=(valNum*2.2046).toFixed(2);
  }
  
}
</script>

{%endblock%}

templates/base_layout.html
{% load static from static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Conversion Calculators</title>
		<link rel="stylesheet" href="{%static 'styles.css'%}">
	</head>
	<body>
		<header class ='wrapper'>
			<h1><a href="{%url 'home' %}">Home</a></h1>
			<nav>
				<ul>
					{%if user.is_authenticated%}
					<li>
						<form class= "logout-link" action="{%url 'accounts:logout'%}" method ='post'>
							{%csrf_token%}
							<button type ="submit">Logout</button>
						</form>
					</li>
					<li><a class="list-link" href="{%url 'calculators:list' %}">Calculator List</a> </li>
					{%else %}
					<li><a href="{%url 'accounts:login'%}">Login</a> </li>
					<li><a href="{%url 'accounts:signup'%}">Signup</a> </li>
					{%endif%}
				</ul>
			</nav>
		</header>
		<div class= "wrapper">
			{%block content%}
			{%endblock%}
		</div>
	</body>
</html>

templates/homepage.html
{%extends 'base_layout.html'%}

{%block content%}



	{%if user.is_authenticated%}
	<div class="home-txt">
		<h1>Welcome to Christopher's Conversion Calculators</h1>
		<p class="home-txt"> Feel free to check out our current conversion calculators <a class="quick-link-home" href="{% url 'calculators:list'%}">here</a>!</p>
	</div>

	{%else %}
		<div class="home-txt">
			<h1>Welcome to Christopher's Conversion Calculators</h1>
			<p class="home-txt"> Login or signup to access the avaliable conversion calculators </p>
		</div>

	{%endif%}
	
{%endblock%}